import { FormEvent, useEffect, useState } from "react";
import { ArrowLeft } from "lucide-react";
import { api } from "../../../api";
import type { Order, OrderStatus } from "../../../types";
import type { Notify } from "../../../app/navigation";
import { AsyncError, Field, OperationBadge, PageHeader } from "../../../shared/components";
import { dateTime, money } from "../../../shared/formatters";
import { orderLabel, transitions } from "../constants";

export function OrderDetailPage({ id, notify, back }: { id: string; notify: Notify; back: () => void }) {
  const [order, setOrder] = useState<Order | null>(null); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const [payment, setPayment] = useState({ amount: '', method: 'Transferencia', reference: '' }); const [proof, setProof] = useState<File | null>(null)
  const load = () => api.order(id).then(setOrder).catch((cause) => setError((cause as Error).message)); useEffect(() => { void load() }, [id])
  if (error) return <><button className="back-button" onClick={back}><ArrowLeft /></button><AsyncError message={error} /></>; if (!order) return <div className="loading-row">Cargando pedido…</div>
  const transition = async (status: OrderStatus) => { setBusy(true); try { setOrder(status === 'CANCELLED' ? await api.cancelOrder(id) : await api.transitionOrder(id, status)); notify(`Pedido actualizado a ${orderLabel[status]}.`) } catch (cause) { notify((cause as Error).message, 'error') } finally { setBusy(false) } }
  const pay = async (event: FormEvent) => { event.preventDefault(); setBusy(true); try { const before = new Set(order.payments.map((item) => item.id)); const updated = await api.registerPayment(id, { amount: payment.amount, method: payment.method, reference: payment.reference || null }); const created = updated.payments.find((item) => !before.has(item.id)); setOrder(updated); if (proof && created) { try { setOrder(await api.uploadPaymentProof(id, created.id, proof)) } catch (cause) { notify(`Pago registrado, pero el comprobante quedó pendiente: ${(cause as Error).message}`, 'error'); return } } setPayment({ amount: '', method: 'Transferencia', reference: '' }); setProof(null); notify('Pago registrado correctamente.') } catch (cause) { notify((cause as Error).message, 'error') } finally { setBusy(false) } }
  const available = order.availableTransitions || transitions[order.status]
  return <><PageHeader eyebrow="Pedido" title={`#${order.id.slice(0, 8)}`} description={`${order.contactName} · ${order.contactEmail}`} back={back} actions={<><OperationBadge value={orderLabel[order.paymentStatus] || order.paymentStatus} tone={order.paymentStatus === 'PAID' ? 'success' : 'warning'} /><OperationBadge value={orderLabel[order.status]} tone={order.status === 'CANCELLED' ? 'danger' : 'neutral'} /></>} /><div className="order-layout"><section className="panel"><div className="panel-heading"><h2>Productos</h2><strong>{money(order.total)}</strong></div><div className="order-summary-lines">{order.lines.map((line) => <div key={line.id}><span><strong>{line.productName}</strong><small>{line.sku} · {line.presentation} · {line.quantity} unidad(es)</small></span><b>{money(line.lineTotal)}</b></div>)}</div><div className="price-result"><div><span>Subtotal</span><strong>{money(order.subtotal)}</strong></div><div><span>Envío</span><strong>{money(order.shippingCost)}</strong></div><div className="commercial"><span>Total</span><strong>{money(order.total)}</strong></div></div></section><section className="panel"><div className="panel-heading"><h2>Entrega</h2></div><div className="description-block"><p>{Object.values(order.shippingAddress).filter(Boolean).join(', ')}</p><small>{order.contactPhone || 'Sin teléfono'} · Tracking: {order.trackingNumber || 'pendiente'}</small></div></section></div>
    {available.length > 0 && <section className="panel order-actions"><div><h2>Próxima acción</h2><p>Las reservas y despachos se ejecutan automáticamente con el cambio de estado.</p></div>{available.map((status) => <button key={status} className={`button ${status === 'CANCELLED' ? 'secondary' : 'primary'}`} disabled={busy} onClick={() => void transition(status)}>{orderLabel[status]}</button>)}</section>}
    {!['CANCELLED', 'DELIVERED'].includes(order.status) && <form className="panel edit-panel" onSubmit={pay}><div className="panel-heading"><div><h2>Registrar pago</h2><p>El comprobante se subirá al almacenamiento privado cuando el backend lo habilite.</p></div></div><div className="form-grid edit-grid"><Field label="Monto"><input inputMode="decimal" value={payment.amount} onChange={(e) => setPayment({ ...payment, amount: e.target.value })} required /></Field><Field label="Método"><input value={payment.method} onChange={(e) => setPayment({ ...payment, method: e.target.value })} required /></Field><Field label="Referencia"><input value={payment.reference} onChange={(e) => setPayment({ ...payment, reference: e.target.value })} /></Field><Field label="Comprobante"><input type="file" accept="application/pdf,image/jpeg,image/png,image/webp" onChange={(e) => setProof(e.target.files?.[0] || null)} /></Field></div><div className="form-actions"><button className="button primary" disabled={busy}>Registrar pago</button></div></form>}
    <section className="panel table-panel"><div className="panel-heading"><h2>Pagos</h2></div><div className="table-wrap"><table><thead><tr><th>Fecha</th><th>Método</th><th>Referencia</th><th>Monto</th><th>Comprobante</th></tr></thead><tbody>{order.payments.map((item) => <tr key={item.id}><td>{dateTime(item.createdAt)}</td><td>{item.method}</td><td>{item.reference || '—'}</td><td>{money(item.amount)}</td><td>{item.proofUrl ? <a href={item.proofUrl} target="_blank" rel="noreferrer">Abrir</a> : '—'}</td></tr>)}</tbody></table></div></section></>
}
